---

- name: Setup required tools and dependencies
  hosts: all
  become: true

  tasks:

    - name: Install the required services
      apt:
        name:
          - nginx
          - git
          - docker.io
          - docker-compose
        state: latest
        update_cache: yes



    - name: Start the services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - nginx
        - docker