---

- name: Setup Docker, Nginx and Git
  hosts: all
  become: true

  tasks:

  - name: Docker repo
    dnf:
      name:
        - dnf-plugins-core

  - name: Config
    shell: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install
    dnf:
      name:
        - git
        - nginx
      state: latest

  - name: Start
    service:
      name: "{{ item }}"
      enabled: true
      state: started
    loop:
      - docker
      - nginx

  - name: Verify
    shell: |
      docker -v
      nginx -v
      git -v
