---

- name: Create working directory, initialize Swarm, and deploy PHP app
  hosts: all
  become: yes

  vars_files: vault.yaml

  tasks:

    - name: Create a project directory
      file:
        path: /opt/my-php-app
        state: directory
        mode: '0755'

    - name: Clone the project repo
      git:
        repo: "https://{{ git_token }}@github.com/pravinraj-marimuthu/CICD-Infra-Setup-for-PHP-application.git"
        dest: /opt/my-php-app
        version: master
        clone: yes

    - name: Initialize Swarm (only if not already initialized)
      shell: docker swarm init
      register: swarm_init
      failed_when: false
      changed_when: "'Error response from daemon: This node is already part of a swarm' not in swarm_init.stderr"

    - name: Deploy the app
      shell: |
        docker stack deploy -c /opt/my-php-app/backend.yaml app