name: Docker Image Build and Push
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Hub registry login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}   

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: pravinrajmarimuthu/php-helloworld:${{ github.sha }}

      - name: Login to EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "--------------------------------------------------------------------------------------"
            cd ~/php
            echo "--------------------------------------------------------------------------------------"
            echo "The tag produced by the build is: ${{ github.sha }}"
            echo "--------------------------------------------------------------------------------------"
            echo "Replacing the image tag in backend.yaml with new image tag..."
            echo "--------------------------------------------------------------------------------------"
            sed -i 's|image: pravinrajmarimuthu/php-helloworld:.*|image: pravinrajmarimuthu/php-helloworld:${{ github.sha }}|' backend.yaml
            echo "Executing the deployment script..."
            ./deploy.sh
            echo "--------------------------------------------------------------------------------------"